default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: kozumeru_dev
  username: kozumeru_dev
  password: kozumeru_dev

test:
  <<: *default
  database: kozumeru_test
  username: kozumeru_dev
  password: kozumeru_dev

production:
  <<: *default
  database: kozumeru_pro
  username: kozumeru_pro
  password: <%= ENV['KOZUMERU_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
