# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: kozumeru_development
  username: kozumeru_development
  password: kozumeru_development

test:
  <<: *default
  database: kozumeru_test
  username: kozumeru_development
  password: kozumeru_development

production:
  <<: *default
  database: kozumeru_production
  username: kozumeru_production
  password: <%= ENV['KOZUMERU_DATABASE_PASSWORD'] %>
